# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use Nginx to serve the app
FROM nginx:alpine
COPY --from=0 /app/dist/contact-manager-app /usr/share/nginx/html

# Expose frontend port
EXPOSE 80
